# Import des templates de jobs pré-configurés
include:
  - project: o/infra/templates
    file: /gitlab-ci/includes/jobs.yaml

stages:
  - test
  - analyze
  - version
  - build
  - deploy

##
# Fetch all versions of decidim-generators, to compile the last
# minor version available for each stable release.
prepare: 
  stage: version
  before_script:
    - apk add --update jq ruby curl bash
  script:
    - bash ./ci_cd/prepare
  artifacts:
    paths: 
      - versions.csv
    expire_in: 1 days

##
# Run a script in the bin folder. Will execute the "$BUILD_SCRIPT" file
.script_runner: &script_runner   
  stage: build
  variables:
    BUILD_SCRIPT: ""
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  dependencies:
    - prepare
  script:
    - echo "45.66.221.1 npm-8ee.hidora.com" >> /etc/hosts
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - sh "./ci_cd/$BUILD_SCRIPT"

🌱:024: 
  <<: *script_runner
  needs: ["prepare"]
  variables:
    BUILD_SCRIPT: "dev"
    DECIDIM_VERSION: "24"
🚀:024: 
  <<: *script_runner
  needs: ["prepare", "🌱:024"]
  variables:
    BUILD_SCRIPT: "production"
    DECIDIM_VERSION: "24"

