# Docker image for Decidim instance.
# ===
# This image is not suited for a development environment.
# This build is a base image to allow to customize your decidim
# installation. 
# 
# The idea behind this process is to expose in the deployed image as few as possible dependancies.
# Reducing this way the number of security issues.
# 
# Arguments
# ===
#   * ALPINE_RUBY_VERSION: the version of alpine ruby to use, without "ruby-" prefix
#   * NODE_VERSION: node version with "v" prefix
#
# Filesystem
# ===
#   Don't import anything from this image as it.
#   You need to extend it to build your own base for your requirements.
#
# Volumes
# ===
# No volumes are exposed.


ARG ALPINE_RUBY_VERSION=2.7.3
# Should exists for alpine, see https://unofficial-builds.nodejs.org/download/release/
ARG NODE_VERSION=v16.13.0 
ARG USER=decidim
ARG DECIDIM_VERSION=0.24.3


FROM ruby:${ALPINE_RUBY_VERSION}-alpine
ARG NODE_VERSION
ARG USER

ENV BUNDLE_JOBS=4 \
    BUNDLE_RETRY=3 \
    NODE_VERSION=$NODE_VERSION \
    RAILS_ROOT=/home/$USER/app \ 
    NVM_DIR=/usr/local/nvm \
    NVM_NODEJS_ORG_MIRROR=https://unofficial-builds.nodejs.org/download/release \
    NVM_ARCH=x64-musl  \
    RAILS_ENV=production \
    RACK_ENV=production\
    USER=$USER \
    # Dummy env variables.
    # This way your deployment provider can already display nice UI
    # on available environments.
    DATABASE_HOST="pg" \
    DATABASE_USERNAME="example" \
    DATABASE_PASSWORD="my-insecure-password" \
    DATABASE_DATABASE="decidim" \
    PORT=3000\
    RAILS_MAX_THREAD=5\
    RAILS_FORCE_SSL="enabled" \
    RAILS_SERVE_STATIC_FILES="false"\
    SECRET_KEY_BASE="quickstart" \
    TZ="Europe/Zurich" \
    RAILS_LOG_DAILY="disabled" \
    RAILS_PID_FILE="tmp/pids/server.pid" \
    RAILS_SERVE_STATIC_FILES="disabled" \
    RAILS_CACHE_MODE="disabled"\
    RAILS_CACHE_REDIS_URL="redis://username:password@redis:6379/0"\
    DECIDIM_BLOCK_SYSTEM="disabled"\
    SAFELIST_IPS="" \
    RAILS_JOB_MODE="default" \
    JOB_REDIS_URL="redis://username:password@redis:6379/1"\
    GEO_HERE_API=""\
    DECIDIM_DEFAULT_LOCALE="fr"\
    DECIDIM_AVAILABLE_LOCALES="fr,en,pt,pt-BR"\
    DECIDIM_CURRENCY_UNIT="CHF"

ENV PATH=$PATH:$NVM_DIR

WORKDIR $RAILS_ROOT

RUN mkdir -p $NVM_DIR

# Install dependencies:
# - build-base: To ensure certain gems can be compiled
# - postgresql-dev postgresql-client: Communicate with postgres through the postgres gem
# - libxslt-dev libxml2-dev: Nokogiri native dependencies
# - imagemagick: for image processing
# - git: for gemfiles using git 
# - bash curl: to download nvm and install it
# - libstdc++: to build NVM
RUN gem update --system && \
    gem install bundler && \
    apk --update --no-cache add \
        build-base \
        tzdata \
        postgresql-dev postgresql-client \
        libxslt-dev libxml2-dev \
        imagemagick \
        git \
        bash curl \
        libstdc++ \
        && rm -rf /var/cache/apk/*

# Install nvm, to have the approriate node version to compile assets
RUN touch $RAILS_ROOT/.profile && \
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash; \
    source $NVM_DIR/nvm.sh; \
    echo "nvm_get_arch() { nvm_echo \"x64-musl\"; }" >> $RAILS_ROOT/.profile; source $RAILS_ROOT/.profile;\
    nvm install $NODE_VERSION



COPY ./bin/* ./bin/

# Run the generator
RUN source $NVM_DIR/nvm.sh; nvm use $NODE_VERSION && \
    gem install decidim -v "$DECIDIM_VERSION" && \
    decidim . && \
    gem cleanup decidim

# Rename migrations, to be consistent over time.
COPY ./ci_cd/scripts/rename-migrations.sh ./.docker/rename-migrations.sh
RUN ./.docker/rename-migrations.sh && rm -rf ./.docker && rm -rf ./.git

# Prepare bundler to work only with production gems.
RUN bundle config set without 'development test' && \
    bundle install && \
    bundle binstubs --all
# Add the overrides
COPY ./overrides/$DECIDIM_VERSION/* ./

