# frozen_string_literal: true
source "https://rubygems.org"
ruby RUBY_VERSION

gem "decidim", "~> 0.24.3"
gem "decidim-calendar"
gem "decidim-decidim_awesome", "~> 0.7.2"
gem "decidim-term_customizer", git: "https://github.com/mainio/decidim-module-term_customizer", branch: "master"
gem "mini_racer"
gem "bootsnap", "~> 1.5", ">= 1.5.1"
gem "puma", "~> 5.1", ">= 5.1.1"
gem "uglifier", "~> 4.2"
gem "redis","~> 4.5.1"
gem "hiredis", "~> 4.5.1"